DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS post;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE showcase (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  next_opening INTEGER NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  css_style TEXT NOT NULL,
  html_page TEXT NOT NULL
);

CREATE TABLE shop_type (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  category TEXT NOT NULL,
  description TEXT NOT NULL
);
CREATE TABLE shops (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  type_id INTEGER NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  opened_on DATE NOT NULL,
  name TEXT NOT NULL,
  FOREIGN KEY (type_id) REFERENCES shop_type (id)
);
CREATE TABLE anniversaries (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  shop_id INTEGER NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  year integer NOT NULL,
  message TEXT NOT NULL,
  FOREIGN KEY (shop_id) REFERENCES shops (id)
);
